use super::{AlertEvent, Severity};
use crate::config::EmailConfig;
use anyhow::{Context, Result};
use lettre::message::header::ContentType;
use lettre::transport::smtp::authentication::Credentials;
use lettre::{AsyncSmtpTransport, AsyncTransport, Message, Tokio1Executor};

/// Send an email alert for a security event via SMTP.
pub async fn send_email_alert(
    config: &EmailConfig,
    event: &AlertEvent,
    hostname: &str,
) -> Result<()> {
    let smtp_host = config
        .smtp_host
        .as_deref()
        .context("SMTP host not configured")?;
    let from = config
        .from
        .as_deref()
        .context("Email 'from' address not configured")?;
    let to_addrs = config
        .to
        .as_ref()
        .context("Email 'to' addresses not configured")?;

    if to_addrs.is_empty() {
        anyhow::bail!("Email 'to' list is empty");
    }

    let severity_label = match event.severity {
        Severity::Critical => "CRITICAL",
        Severity::Warning => "WARNING",
        Severity::Info => "INFO",
    };

    let subject = format!(
        "[Guardian Shell] {} — {} on {} (agent: {})",
        severity_label,
        event.action.to_string().to_uppercase(),
        event.path,
        event.agent_name,
    );

    let body = format!(
        "Guardian Shell Security Alert\n\
         ================================\n\n\
         Severity:  {severity}\n\
         Event:     {event_type}\n\
         Action:    {action}\n\
         Timestamp: {timestamp}\n\n\
         Agent:     {agent}\n\
         PID:       {pid} ({comm})\n\
         Identity:  {identity}\n\
         Path:      {path}\n\
         Flags:     {flags}\n\
         Mode:      {mode}\n\
         Host:      {host}\n\n\
         ---\n\
         This alert was generated by Guardian Shell.\n",
        severity = event.severity,
        event_type = event.event_type,
        action = event.action,
        timestamp = event.timestamp.to_rfc3339_opts(chrono::SecondsFormat::Secs, true),
        agent = event.agent_name,
        pid = event.pid,
        comm = event.comm,
        identity = event.identity_method,
        path = event.path,
        flags = event.access_mode,
        mode = event.policy_mode,
        host = hostname,
    );

    // Build the email
    let mut email_builder = Message::builder()
        .from(from.parse().with_context(|| format!("Invalid from address: {}", from))?)
        .subject(subject);

    for to in to_addrs {
        email_builder =
            email_builder.to(to.parse().with_context(|| format!("Invalid to address: {}", to))?);
    }

    let email = email_builder
        .header(ContentType::TEXT_PLAIN)
        .body(body)
        .context("Failed to build email message")?;

    // Build SMTP transport
    let smtp_port = config.smtp_port.unwrap_or(587);
    let mut transport_builder = AsyncSmtpTransport::<Tokio1Executor>::starttls_relay(smtp_host)
        .with_context(|| format!("Failed to create SMTP transport for {}", smtp_host))?
        .port(smtp_port);

    if let (Some(ref username), Some(ref password)) = (&config.username, &config.password) {
        transport_builder =
            transport_builder.credentials(Credentials::new(username.clone(), password.clone()));
    }

    let mailer = transport_builder.build();

    mailer
        .send(email)
        .await
        .context("Failed to send email alert")?;

    Ok(())
}
